### ISSUE TITLE
Bug: Incorrect result for minimum products sold

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-52/bangazon-api-sherwin025#3]
Clients can request a list of products that have sold at least the specified number of items using the following URL scheme.

http://localhost:8000/products?number_sold=20

This should return products that have been sold 20+ times. This feature is currently not working.

**Comment by sherwin025** [comment]
change line 174 to end in gte instead of lt, also added a q method to line 173 to filter the payment type to match tickets
