### ISSUE TITLE
Bug: Can't remove an item from the cart

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-52/bangazon-api-sherwin025#4]
Customers are complaining that they can't remove an item from the cart after it has been added.

When the client performs a DELETE request to the `/products/{id}/remove_from_order` resource, it should remove the specified item from the user's cart.

**Comment by sherwin025** [comment]
added codes on product view lines 256-257. it gets the specific orderproduct line in the database that corresponds with that request and it deletes it removing it from the cart
